### ISSUE TITLE
Makefile doesn't work on MacOS

### ISSUE THREAD

**Issue by Zeitungsleser** [openbikesensor/OpenBikeSensor3dPrintableCase#59]
The Makefile to get the files with logo does not work on Mac, cause openSCAD isn't installed at /usr/bin/openscad.

**Comment by gluap** [comment]
Does it work on macos with just openscad instead of the absolute path?

**Comment by Zeitungsleser** [comment]
The first approach didn't work. The second approach results in the following error: 
```
make OPENSCAD=/Applications/OpenSCAD.app all
/Applications/OpenSCAD.app -q -D orient_for_printing=true -o export/MainCase/MainCaseLid.stl src/MainCase/MainCaseLid.scad
bash: /Applications/OpenSCAD.app: is a directory
make: *** [export/MainCase/MainCaseLid.stl] Error 126
```

**Comment by gluap** [comment]
`.app` files are not really executables but packed folders that contain an executable somewhere below along with other data. They can't be run directly from the command line, but you may be able to find an openscad executable somewhere in the .app folder. You'll need to use the command line to investigate, finder hides the directory contents from the user. Another way would be to install openscad with homebrew instead of the `.app` package (yielding an openscad binary in the bin folder used by brew).
